import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased `}>
        <Toaster richColors position="top-right" />
        <main className="bg-black py-10 sm:px-10 px-2 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
